### ISSUE TITLE
[Feature] [Modpack] Packwiz Modpack Support

### ISSUE THREAD

**Issue by Merith-TK** [PolyMC/PolyMC#340]
### Role

I am a modpack player and maintainer

### Suggestion

support the packwiz bootstrap modpack format

### Benefit

just another way for players to manually add modpacks with less complications

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

https://gitlab.com/Merith-TK/vanillia-modpack

the link above is a modpack I maintain for the multimc launcher, as you can see in `instance.cfg`, I am forced to bundle an extra jar, and as shown by the `multimc` section of the make file, I have to maintain and bundle the launcher configs seperately than the actual modpack itself, 

[Packwiz](https://packwiz.infra.link/) can be used to make modpacks for Curseforge, and Modrinth platforms, but can also be used to make a modpack for multimc and technic platforms (as shown in the previously stated makefile)
but in order to do this, maintainers have to bundle extra multimc configs and worry about maintaining those should something break.

The idea for implementation, would be at the "import modpack" page, where when it requests a modpack.zip file or link, also accept a link that ends in `pack.toml`, like so `https://gitlab.com/Merith-TK/vanillia-modpack/-/raw/main/.minecraft/pack.toml`,

packwiz's format allows for securly acquiring mods from sources such as modrinth or curseforge, as the mod.toml files contain all the information on where to get them,

example
https://gitlab.com/Merith-TK/vanillia-modpack/-/blob/main/.minecraft/mods/lithium.toml

```toml
name = "Lithium (Fabric)"
filename = "lithium-fabric-mc1.18.1-0.7.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3659/182/lithium-fabric-mc1.18.1-0.7.8.jar"
hash-format = "sha1"
hash = "8b7cd216fee54b9acc261005cae5acbc856b1933"

[update]
[update.curseforge]
file-id = 3659182
project-id = 360438
```

Persisting the pack.toml, you could run the initial checks following the same logic that [Packwiz Installer Bootstrap](https://github.com/packwiz/packwiz-installer-bootstrap/) uses to keep the modpack up to date in the future
