### ISSUE TITLE
Add WinGet Releaser

### ISSUE THREAD

**Issue by russellbanks** [PolyMC/PolyMC#793]
### Role

I'm a winget-pkgs contributor and user of PolyMC :)

### Suggestion

Add [WinGet Releaser](https://bittu.eu.org/docs/wr-intro/)

### Benefit

To automate the publishing of packages to winget-pkgs

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

I understand that @FayneAldan is the one that has been mantaining PolyMC on the winget-pkgs repository. However, this process could be automated with a workflow, using [WinGet Releaser](https://bittu.eu.org/docs/wr-intro/). This is a workflow that will run on release and automatically create a pull request with the updated manifest, without the need for manual intervention. If this is something the maintainers would like, I'd be more than happy to create a pull request for this.

This could also make the [community-maintained CLI install](https://polymc.org/download/#advanced-windows-install-options) become more of an 'officially automated' CLI install.

It would look a bit like this:
```yaml
name: Publish to WinGet
on:
  release:
    types: [released]

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@latest
        with:
          identifier: PolyMC.PolyMC
          installers-regex: '\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
```
